version: '2'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: api
    ports:
    - "8080:8080"
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    image: admin
    ports:
     - "8079:80"
